name: Frontend Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js environment
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'

    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Install dependencies
      run: npm install

    - name: Build the React app
      run: npm run build

    - name: Build and Push Docker image to Docker hub
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
        image: zguan0101/coastal_casa_finder_web
        tags: latest
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: SSH to AWS
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.AWS_USERNAME }}
        key: ${{ secrets.PRIVATE_KEY }}
        script: |
          echo "Connected to server successfully"
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker pull ${{ secrets.DOCKER_USERNAME }}/coastal_casa_finder_web
          docker stop coastal_casa_finder_web
          docker rm coastal_casa_finder_web
          docker run -d -p 3000:80 --name coastal_casa_finder_web ${{ secrets.DOCKER_USERNAME }}/coastal_casa_finder_web
          echo "All commands are done, check http://18.196.64.140:3000 for this deployment"