name: PR Check 

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          yarn install --frozen-lockfile
          yarn build

      - name: Build and test
        run: |
          yarn test --watchAll=false --coverage --maxWorkers=4
      

      - name: Send Slack Workflow Result
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: workflow-results
          SLACK_COLOR: ${{ job.status }}
          SLACK_USERNAME: Github-Bot
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: always()
