name: PR Check 

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          yarn install --frozen-lockfile
          yarn build

      - name: Build and test
        run: |
          yarn test --watchAll=false --coverage --maxWorkers=4